stages:
  - build
  - deploy

build-image:
  stage: build
  image: moby/buildkit:rootless
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildctl-daemonless.sh login "$CI_REGISTRY" --username "$CI_REGISTRY_USER" --password-stdin
  script:
    - buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --output type=image,name="$CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG",push=true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: on_success

update-production:
  image: bitnami/kubectl:latest
  stage: deploy
  before_script:
    - export KUBECONFIG="$KUBECONFIG_FILE"
  script:
    - kubectl apply -f /home/ruk/k3s/blog/deployment.yaml
    - kubectl rollout status deployment/blog -n blog --timeout=120s
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build-image-branch:
  stage: build
  image: moby/buildkit:rootless
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  script:
    - buildctl-daemonless.sh build \
        --frontend dockerfile.v0 \
        --local context=. \
        --local dockerfile=. \
        --output type=image,name="$CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG",push=true
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'