services:
  xool:
    build:
      target: base
    volumes:
      - .:/usr/src/app
    command: dev
    networks:
      - docker_default
      - default
    environment:
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - LGTM_HOST=l.localhost
      - CLIENT_ID=
      - CLIENT_SECRET=
      - HASH=
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
    labels:
      - "traefik.http.routers.xool.rule=Host(`x.localhost`) || Host(`l.localhost`)"
      - "traefik.http.routers.xool.tls=true"

networks:
  docker_default:
    external: true
    name: docker_default
