services:
  xool:
    build:
      target: base
    volumes:
      - .:/usr/src/app
    command: dev
    networks:
      - docker_default
      - default
    environment:
      - HOST=x.localhost
      - CLIENT_ID=
      - CLIENT_SECRET=
      - HASH=
    labels:
      - "traefik.http.routers.xool.rule=Host(`x.localhost`)"
      - "traefik.http.routers.xool.tls=true"
    depends_on:
      - db
      
  xool-web:
    image: nginx
    volumes:
      - ./images:/usr/share/nginx/html/images
    networks:
      - docker_default
    labels:
      - "traefik.http.routers.xool-web.rule=Host(`x.localhost`) && PathPrefix(`/images`)"
      - "traefik.http.routers.xool-web.tls=true"

  db:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_DATABASE=xool
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    labels:
      - "traefik.enable=false"

volumes:
  mongo:

networks:
  docker_default:
    external: true
    name: docker_default