apiVersion: apps/v1
kind: Deployment
metadata:
  name: xool
  namespace: xool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xool
  template:
    metadata:
      labels:
        app: xool
    spec:
      containers:
        - name: xool
          image: ghcr.io/danything/xool:8e688f61dfee4f9a9bab06cfab1a77d6539b413e
          ports:
            - containerPort: 3000
          env:
            - name: ORIGIN
              value: https://x.doany.io
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: xool-secrets
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: xool-secrets
                  key: client-secret
            - name: HASH
              valueFrom:
                secretKeyRef:
                  name: xool-secrets
                  key: hash
          volumeMounts:
            - name: xool-images
              mountPath: /usr/src/app/images
            - name: xool-db
              mountPath: /usr/src/app/data
      volumes:
        - name: xool-images
          persistentVolumeClaim:
            claimName: xool-images
        - name: xool-db
          persistentVolumeClaim:
            claimName: xool-db
