apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xool
  namespace: xool
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: mydnschallenge
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - x.doany.io
  rules:
    - host: x.doany.io
      http:
        paths:
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: xool
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xool
                port:
                  number: 3000
